name: jd_joy_feed

on:
  schedule:
    - cron: '* */4 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Run a one-line script
        run: echo Hello, world! +%Y-%m-%d
